version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-pagamentos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagamentos
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  api:
    container_name: ms-pagamentos
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: DEFAULT
      MYSQL_URL: jdbc:mysql://mysql:3306/pagamentos
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
